export const SKILLS_AND_TOOLS: string[] = [
  'JavaScript',
  'TypeScript',
  'React (Class-Components & Hooks)',
  'Redux',
  'Redux Toolkit',
  'Node.js (Express, JSON-server)',
  'Git',
  'REST API',
  'Axios',
  'WebSockets',
  'JEST',
  'React Testing Library',
  'MongoDB',
  'SASS',
  'CSS',
  'Bootstrap',
  'Material-UI',
  'Tailwind',
  'HTML',
  'BEM',
  'Webpack',
  'ESLint',
  'Postman',
  'Swagger',
  'Figma',
  'Scrum',
  'Kanban (Trello)',
];

export enum ContactHref {
  telegram = 'https://t.me/mortally_happy',
  linkedin = 'https://www.linkedin.com/in/egor-tabunov/',
  email = 'mailto:vonubat@gmail.com',
  mobile = 'tel:+375-29-277-57-43',
  skype = 'skype:homeanagar?chat',
  github = 'https://github.com/Vonubat',
  location = 'https://goo.gl/maps/Dyu6EhVKdz56ZNV37',
}
