export const SKILLS_AND_TOOLS: string[] = [
  'JavaScript',
  'TypeScript',
  'React (Class-Components & Hooks)',
  'Redux',
  'Redux Toolkit',
  'Node.js (Express, JSON-server)',
  'Git',
  'REST API',
  'Axios',
  'WebSockets',
  'JEST',
  'React Testing Library',
  'MongoDB',
  'SASS',
  'CSS',
  'Bootstrap',
  'Material-UI',
  'Tailwind',
  'HTML',
  'BEM',
  'Webpack',
  'ESLint',
  'Postman',
  'Swagger',
  'Figma',
  'Scrum',
  'Kanban (Trello)',
];
